mlflow:
  tracking_uri: "http://localhost:5000"    # or your MLflow tracking server URI
  experiment_name: "My_Experiment"

data:
  file_path: "data/dataset.csv"           # your dataset CSV file (ensure it exists)
  target_column: "target"                    # the target column name

models:
  Gradient Boosting:
    n_estimators: [100, 150, 200]
    learning_rate: [0.01, 0.05, 0.1]
    max_depth: [3, 5, 7]
    subsample: [0.6, 0.8, 1.0]
    validation_fraction: [0.1]
    n_iter_no_change: [10]
    tol: [0.0001]
    
  Random Forest:
    n_estimators: [100, 150, 200]
    max_depth: [None, 5, 10]
    min_samples_split: [2, 4, 6]
    min_samples_leaf: [1, 2, 4]
    max_features: ["auto", "sqrt"]
    
  Logistic Regression:
    C: [0.1, 1, 10]
    penalty: ["l1", "l2"]
    
  SVM:
    C: [0.1, 1, 10]
    kernel: ["linear", "rbf"]
    
  KNN:
    n_neighbors: [3, 5, 7]
    weights: ["uniform", "distance"]
