channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=24.3.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - imbalanced-learn==0.13.0
  - lz4==4.4.3
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
